version: '3.8'

services:
  myapp-server:
    build:
      context: .
      dockerfile: MyApp.Server/Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    ports:
      - "5244:5244"
    environment:
      ASPNETCORE_URLS: "http://+:5244"
